#include QMK_KEYBOARD_H

#define _QWERTY 0
#define _LOWER 1
#define _RAISE 2

#define RAISE MO(_RAISE)
#define LOWER MO(_LOWER)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_5x6(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_GRV, KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSLS, KC_CAPS, KC_A, KC_R, KC_S, KC_T, KC_D, KC_H, KC_N, KC_E, KC_I, KC_O, KC_QUOT, LGUI(KC_SPC), LCTL_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(2,KC_PSCR), KC_F11, KC_F12, KC_LBRC, KC_RBRC, KC_BSPC, LSFT_T(KC_SPC), MO(1), KC_ENT, KC_DEL, KC_LALT, KC_PGUP, KC_PGDN, KC_INS, KC_LGUI, KC_SCRL, KC_PAUS),
        [1] = LAYOUT_5x6(KC_ESC, KC_NO, KC_NO, KC_HASH, KC_DLR, KC_NO, KC_NO, KC_PERC, KC_CIRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_EXLM, KC_AT, KC_UP, KC_EQL, KC_ASTR, KC_PLUS, KC_7, KC_8, KC_9, KC_AMPR, KC_PIPE, KC_NO, KC_LPRN, KC_LEFT, KC_DOWN, KC_RGHT, KC_RPRN, KC_PMNS, KC_4, KC_5, KC_6, KC_0, KC_NO, LCTL(KC_Z), KC_LCTL, KC_HOME, KC_APP, KC_END, KC_NO, KC_UNDS, KC_1, KC_2, KC_3, KC_NO, SGUI(KC_S), KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC, LSFT_T(KC_SPC), KC_NO, KC_CALC, KC_NO, KC_LALT, G(C(KC_LEFT)), G(C(KC_RGHT)), KC_NO, KC_NO, KC_NO, KC_NO),
        [2] = LAYOUT_5x6(QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NUM, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_NO, KC_NO, KC_F24, KC_F23, KC_F22, KC_MPRV, KC_MNXT, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_P0, KC_NO, KC_F21, KC_F20, KC_F19, KC_MUTE, KC_MPLY, KC_NO, KC_LCTL, KC_P1, KC_P2, KC_P3, KC_NO, KC_NO, KC_F18, KC_F17, KC_F16, KC_F15, KC_NO, KC_NO, KC_NO, KC_F14, KC_F13, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};